# filenet-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: icn-svc
  namespace: filenet
  labels:
    app: icn
spec:
  selector:
    app: icn
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 30081
  - name: https
    protocol: TCP
    port: 9443
    targetPort: 9443
    nodePort: 30444
  type: NodePort
