# filenet-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ier-svc
  namespace: filenet
  labels:
    app: ier
spec:
  selector:
    app: ier
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 30083
  - name: https
    protocol: TCP
    port: 9443
    targetPort: 9443
    nodePort: 30446
  type: NodePort
