apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: infra
spec:
  selector:
    app: postgres
  ports:
  - name: psql
    protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30001
  type: NodePort
 
