apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi