apiVersion: v1
kind: ConfigMap
metadata:
  name: isvd-server-config
  namespace: infra
data:
  config.yaml: |
    general:
      id: dev-server
      license: 
        accept: limited
        key: <license_key>
      admin:
        dn: cn=root
        pwd: Password1
        
      json-logging: false
      
      ports:
        ldap: 9389
        ldaps: 9636
        
      admin: 
        dn: cn=root
        pwd: Password1
      
      pwd-encryption: none
      pwd-policy:
        enabled: false
      
    server:
      replication:
        admin:
          dn: cn=replcred
          pwd: Password1
          
      suffixes:
        - dn: dc=demodom,dc=nl
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  namespace: infra
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      imagePullSecrets:
        - name: ibm-entitlement-key    

      containers:
      - name: verify-directory
        image: icr.io/isvd/verify-directory-server:10.0.4.0
        imagePullPolicy: IfNotPresent

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
 
        ports:
        - containerPort: 9080
          name: http
        - containerPort: 9443
          name: https
        - containerPort: 9389
          name: ldap
        - containerPort: 9636
          name: ldaps
          
        env:
        - name: YAML_CONFIG_FILE
          value: /var/isvd/config/config.yaml
          
        volumeMounts:
        - name: ldap-volume
          mountPath: /var/isvd/data
          subPath: data
        - name: ldap-volume
          mountPath: /var/isvd/config
          subPath: config
        - name: config-volume
          mountPath: /var/isvd/config/config.yaml
          subPath: config.yaml
          
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
            
        livenessProbe:
          tcpSocket:
            port: 9389
          initialDelaySeconds: 60
          periodSeconds: 30
          
        readinessProbe:
          tcpSocket:
            port: 9389
          initialDelaySeconds: 30
          periodSeconds: 10
          
      volumes:
      - name: ldap-volume
        persistentVolumeClaim:
          claimName: ldap-pvc
      - name: config-volume
        configMap:
          name: isvd-server-config
          items:
          - key: config.yaml
            path: config.yaml