apiVersion: v1
kind: Service
metadata:
  name: ldap-svc
  namespace: infra
  labels:
    app: ldap
spec:
  selector:
    app: ldap
  ports:
    - port: 9389
      name: ldap
      targetPort: 9389
      nodePort: 30389
      protocol: TCP
    - port: 9636
      name: ldaps
      targetPort: 9636
      nodePort: 30636
      protocol: TCP
    - port: 9443
      name: admin
      targetPort: 9443
      nodePort: 31943
      protocol: TCP
  type: NodePort