# filenet-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tm-svc
  namespace: filenet
  labels:
    app: tm
spec:
  selector:
    app: tm
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 30084
  - name: https
    protocol: TCP
    port: 9443
    targetPort: 9443
    nodePort: 30447
  type: NodePort
