# filenet-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cpe-svc
  namespace: filenet
  labels:
    app: cpe
spec:
  selector:
    app: cpe
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 30080
  - name: https
    protocol: TCP
    port: 9443
    targetPort: 9443
    nodePort: 30443
  type: NodePort
