apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpe
  namespace: filenet
  labels:
    app: cpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpe
  template:
    metadata:
      labels:
        app: cpe    
    spec:
      imagePullSecrets:
        - name: ibm-entitlement-key    
        
      serviceAccountName: default 

      containers:
      - name: cpe
        image: cp.icr.io/cp/cp4a/fncm/cpe:ga-570-p8cpe
        imagePullPolicy: "IfNotPresent"

        ports:
        - containerPort: 9080
          name: http
        - containerPort: 9443
          name: https

        securityContext:
          capabilities:
            drop: ["ALL"]
          privileged: false
          runAsUser: 1000140000
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
        
        env:
        - name: LICENSE
          value: accept
        - name: LICENSEMODEL
          value: FNCM.PVUNonProd
        - name: TZ
          value: Europe/Amsterdam
        - name: LOG_FORMAT
          value: json

        - name: disableFIPS
          value: "true"
        - name: CPESTATICPORT
          value: "false"
        - name: CONTAINERTYPE
          value: "1"          
        - name: JVM_INITIAL_HEAP_PERCENTAGE
          value: '18'
        - name: JVM_MAX_HEAP_PERCENTAGE
          value: '33'
        - name: JVM_CUSTOMIZE_OPTIONS
          value: "-Dcom.ibm.ws.session.cookie.secure=false -DInvalidateOnUnauthorizedSessionRequestException=false -Dcom.ibm.ws.session.useContextRootAsCookiePath=false -Dcom.filenet.authentication.wsi.AutoDetectAuthToken=true "
        - name: DISABLE_BASIC_AUTH
          value: 'true'
        - name: ENV_PROP_FILE
          value: /opt/ibm/wlp/usr/servers/defaultServer/resources/security/environment.properties

        - name: GATEWAY_SERVICE_URI
          value: 'http://filenet-svc.filenet.svc.cluster.local:9080/WSCPEService/WSCPEServiceSoapService'
        - name: GCDJNDINAME
          value: FNGCDDS
        - name: GCDJNDIXANAME
          value: FNGCDDSXA
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
              
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "4Gi"
          limits:
            memory: "3072Mi"
            cpu: "1"
            ephemeral-storage: "4Gi"

        volumeMounts:
        # FileNet CPE specific paths related to WLP defaultServer
        - name: cpe-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/logs
          subPath: logs
        - name: cpe-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/FileNet
          subPath: FileNet
        - name: cpe-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/lib/bootstrap
          subPath: bootstrap
          
        - name: cpe-volume
          mountPath: /opt/ibm/icmrules
          subPath: opt/icmrules
        - name: cpe-volume
          mountPath: /opt/ibm/textext
          subPath: opt/textext
        - name: cpe-volume
          mountPath: /opt/ibm/asa
          subPath: opt/asa
        - name: cpe-volume
          mountPath: /opt/filebeat
          subPath: opt/filebeat
        - name: cpe-volume
          mountPath: /opt/tivoli
          subPath: opt/tivoli
        - name: cpe-volume
          mountPath: /licenses
          subPath: licenses

        - name: tls-volume
          mountPath: /shared/tls/pkcs12
          
        #- name: config-volume
        #  mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/ibm_wsatomic.xml
        #  subPath: ibm_wsatomic.xml
        - name: config-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/ibm_ldap_custom_default1.xml
          subPath: ibm_ldap_custom_default1.xml
        - name: config-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/ibm_ldap_federated.xml
          subPath: ibm_ldap_federated.xml
        - name: config-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/PostgreSQLJDBCDriver.xml
          subPath: PostgreSQLJDBCDriver.xml
        - name: config-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/ibm_GCD.xml
          subPath: ibm_GCD.xml
        - name: config-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/ibm_OS1.xml
          subPath: ibm_OS1.xml
        - name: config-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/ibm_OS2.xml
          subPath: ibm_OS2.xml
        - name: config-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/http-session.xml
          subPath: http-session.xml
        - name: config-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/ibm_CORS.xml
          subPath: ibm_CORS.xml
        - name: config-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/resources/security/environment.properties
          subPath: environment.properties
        - name: config-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/ibm_custom-ssl.xml
          subPath: ibm_custom-ssl.xml
        - name: config-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/ibm_custom-ltpa.xml
          subPath: ibm_custom-ltpa.xml
        - name: config-volume
          mountPath: /opt/ibm/wlp/usr/servers/defaultServer/resources/security/custom-ltpa.keys
          subPath: custom-ltpa.keys

      volumes:
      - name: cpe-volume
        persistentVolumeClaim:
          claimName: filenet-pvc
      - name: config-volume
        configMap:
          name: filenet-config
      - name: tls-volume
        configMap:
          name: cpe-tls-volume