apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphql-pvc
  namespace: filenet
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi