# filenet-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: graphql-svc
  namespace: filenet
  labels:
    app: graphql
spec:
  selector:
    app: graphql
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 30082
  - name: https
    protocol: TCP
    port: 9443
    targetPort: 9443
    nodePort: 30445
  type: NodePort
